# Generated by Django 4.1.2 on 2022-10-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task_is_completed_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=128)),
                (
                    'description',
                    models.TextField(blank=True, max_length=512, null=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(to='todo.taskcategory'),
        ),
    ]
