# Generated by Django 4.1.2 on 2022-10-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_task_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcategory',
            options={'verbose_name_plural': 'task categories'},
        ),
    ]
